#!/bin/bash
for num in {50..100};
do
    prime=1
    for ((i = 2; i < num; i++)); do
        if [ $((num % i)) -eq 0 ]; then
            prime=0
            break
        fi
    done

    if [ $prime -eq 1 ];
    then
        echo $num
    fi
done

